[package]
name = "day-2"
version = "0.1.0"
authors = ["Joe Banks <joseph@josephbanks.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
